pipeline {
  agent any
  stages {
    stage('Initialise the modules') {
      steps {
        sh 'terraform init'
      }
    }
    stage('Perform Testing of the Code') {
      steps {
        sh 'terraform plan -out myplan'
      }
    }
    stage('Apply the code if pass the test') {
      steps {
        sh 'terraform apply -input=false myplan'
      }
    }
    stage('Destroy the resources') {
      steps {
        sh 'terraform destroy -auto-approve'
      }
    }
  }
}